apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crazy-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gitlab.ndreadno.com/root/inseption_of_things.git'
    path: .
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
