apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crazy-app
  namespace: gitlab
spec:
  project: default
  source:
    repoURL: 'https://github.com/zcolleen/inseption_of_things.git'
    path: configs
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
