
imagePullPolicy: IfNotPresent

gitlabUrl: https://gitlab.com

runnerRegistrationToken: "PtNgSXKtxzF5YsHA4mpR"

terminationGracePeriodSeconds: 3600

concurrent: 10

checkInterval: 30

rbac:
  create: true

  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]

  clusterWideAccess: true

  podSecurityPolicy:
    enabled: false
    resourceNames:
    - gitlab-runner

metrics:
  enabled: true

  portName: metrics

  port: 9252

  serviceMonitor:
    enabled: false

service:
  enabled: false

  type: ClusterIP


runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "dev"
        image = "ubuntu:16.04"
        url = "https://gitlab.com/"
        token = "PtNgSXKtxzF5YsHA4mpR"


  tags: "deploy"

  name: "deploy-runner"

  cache: {}

  builds: {}

  services: {}

  helpers: {}

securityContext:
  runAsUser: 100
  fsGroup: 65533

resources: {}

affinity: {}


nodeSelector: {}

tolerations: []

hostAliases: []

podAnnotations: {}

podLabels: {}

secrets: []

configMaps: {}
