

VAGRANTFILE_API_VERSION = "2"


ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "hashicorp/bionic64"
    config.vm.boot_timeout = 120

    config.vm.network :private_network, ip: "192.168.42.112"
    config.vm.network "forwarded_port", guest: 80, host:80


	config.vm.provider "virtualbox" do |v|
        v.cpus = 4
		v.memory = "10000"
	end

    
    config.vm.provision "file", source: "./confs", destination: "$HOME/config"
    
    config.vm.provision "shell", path: "scripts/scr.sh"


end
