apiVersion: apps/v1
kind: Deployment
metadata:
  name: crazy-deployment
spec:
  selector:
    matchLabels:
      app: ndreadno
  replicas: 1
  template:
    metadata:
      labels:
        app: ndreadno
    spec:
      containers:
      - name: ndreadno
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: crazy-service
spec:
  type: ClusterIP
  selector:
    app: ndreadno
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crazy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "crazy"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: crazy-service
              port:
                number: 8888
