# -*- mode: ruby -*-
# vi: set ft=ruby :

SETTINGS = "./confs/master.yaml"
   
CONF = YAML::load_file(SETTINGS)["server"]

Vagrant.configure("2") do |config|
	config.vm.box = CONF["box"]

    config.vm.define CONF["name"] do |server|
        server.vm.provider CONF["provider"] do |vbox|
            vbox.name = CONF["name"]
            vbox.cpus = CONF["cpus"]
            vbox.memory = CONF["memory"]
        end

        server.vm.network "private_network", ip: CONF["ip"]
        server.vm.network "forwarded_port", guest: 80, host:8080
        server.vm.network "forwarded_port", guest: 443, host:8443
        server.vm.hostname = CONF["name"]
		server.vm.provision "file", source: "confs/app.yaml", destination: "/tmp/app.yaml"
		server.vm.provision "shell", path: "scripts/bootstrap.sh", privileged: false
		server.vm.provision "shell", path: "scripts/deploy.sh",
			privileged: false, env: { "CLUSTER": CONF["name"] }
    end

end
